var list = [
    'Dance Party', 

    'Call or message a friend you have not talked to for a while',
    'Attempt an amazing but complex dessert recipe.',
  'Go into a shop and buy a food product that you have never tried before.',
    'Skydive!',
    'Go for a walk.',
    'Canoe.',
    'Go camping.',
    'Go fishing',
    'Dawn sail or kayak.',
    'Go swimming in the local pool.',
    'Surf',
    'Go swimming outside (in a lake or sea).',
    'Go to the park.',
    'Buy or sell stuff at a car boot sale.',
    'Go to a theme park.',
    'Go paragliding.',
    'Go to your local zoo.',
    'Nighttime Activities',
    'Watch a film outside using a projector and a bed sheet.',
    'Check your local heritage website for an exciting place to rent out for a night.',
    'Host an all-night gaming marathon.',
    'Arrange a night out with friends.',
    'New Skills to Pick Up',
    'Learn to skate.',
    'Learn Morse code.',
    'Learn a simple tune on an instrument via YouTube.',
    'Learn your name in different languages.',
    'Learn the words to a song.',
    'Find out how to survive a bear attack.',
    'Learn a magic trick.',
    'Build a treehouse.',
    'Activities That Benefit Others',
    'Give money to charity.',
    'Cook a fancy meal for friends or family.',
    'Volunteer at a charity shop to help those less fortunate.',
    'Plan a surprise party for a friend.',
    'Things to Do With Friends',
    'Have a pillow fight.',
    'Go bowling.',
    'Throw a spontaneous party.',
    'Play a board game.',
    'Think about getting a pet.',
    'Think about getting a pet.',
    
    'Collect stamps.',
    'Collect coins.',
    'Watch a film.',
    'Go to church.',
    'Practice your shower singing.',
   'Make an omelet—experiment with new flavors.',
    'Think about and research getting a pet.',
    'Start a woodworking project (e.g., a CD holder or shelf).',
    'Find and subscribe to a magazine. There is a magazine out there for everyone',
    'Start planning your next holiday.',
    'Read your local news. You can buy your city paper from a local shop',
    'Buy a poster or picture for your wall.',
    'Buy a box set of your favorite television series.',
    'Register to vote.',
    'Sort your CD/book collection.',
    'Plant something in a pot on your window ledge or out in the garden.',
    'Self-Improvement Activities',
    'Enter a triathlon.',
    'Write down some 1-, 3-, and 5-year goals.',
    'Train for a 10km race.',
    'Work on your math skills.',
    'Go to the gym.',
    'Try to eat healthy all day—or all week!',
    'See what courses are available at your local higher education center.',
    'Make a small investment, e.g., shares, gold bullion bar.',
    'Give your brain a workout. Do a puzzle in the paper or take a grammar quiz online.',
    
    'Make a cake without following a recipe and see how it turns out.',
    'Rearrange your furniture.',
    'Buy your town local produce.',
    'Have a Nerf or BB gun battle. Make sure you wear suitable clothing!',
    'Rent a movie series and buy a big bag of snacks to eat as you binge.',
    'Plant vegetables. Look online to see what you can plant this month.',
    'Make homemade ice cream.',
    'Lie down and listen to music.',
    'Make a list of things you both want to achieve in the next ten years.',
]

function newList() {
    var randomNumber = Math.floor(Math.random() * (list.length));
    document.getElementById('listDisplay').innerHTML = list[randomNumber];
    }






