var list = [
    'Dance Party', 

    'Call or message a friend you have not talked to for a while',
    'Attempt an amazing but complex dessert recipe.',
  'Go into a shop and buy a food product that you have never tried before.',
    'Skydive!',
    'Go for a walk.',
    'Canoe.',
    'Go camping.',
    'Go fishing',
    'Dawn sail or kayak.',
    'Go swimming in the local pool.',
    'Surf',
    'Go swimming outside (in a lake or sea).',
    'Go to the park.',
    'Buy or sell stuff at a car boot sale.',
    'Go to a theme park.',
    'Go paragliding.',
    'Go to your local zoo.',
    'Nighttime Activities',
    'Watch a film outside using a projector and a bed sheet.',
    'Check your local heritage website for an exciting place to rent out for a night.',
    'Host an all-night gaming marathon.',
    'Arrange a night out with friends.',
    'New Skills to Pick Up',
    'Learn to skate.',
    'Learn Morse code.',
    'Learn a simple tune on an instrument via YouTube.',
    'Learn your name in different languages.',
    'Learn the words to a song.',
    'Find out how to survive a bear attack.',
    'Learn a magic trick.',
    'Build a treehouse.',
    'Activities That Benefit Others',
    'Give money to charity.',
    'Cook a fancy meal for friends or family.',
    'Volunteer at a charity shop to help those less fortunate.',
    'Plan a surprise party for a friend.',
    'Things to Do With Friends',
    'Have a pillow fight.',
    'Go bowling.',
    'Throw a spontaneous party.',
    'Play a board game.',
    'Think about getting a pet.',
    'Think about getting a pet.',
    'Collect stamps.',
    'Collect coins.',
    'Watch a film.',
    'Go to church.',
    'Practice your shower singing.',
   'Make an omelet—experiment with new flavors.',
    'Think about and research getting a pet.',
    'Start a woodworking project (e.g., a CD holder or shelf).',
    'Find and subscribe to a magazine. There is a magazine out there for everyone',
    'Start planning your next holiday.',
    'Read your local news. You can buy your city paper from a local shop',
    'Buy a poster or picture for your wall.',
    'Buy a box set of your favorite television series.',
    'Register to vote.',
    'Sort your CD/book collection.',
    'Plant something in a pot on your window ledge or out in the garden.',
    'Self-Improvement Activities',
    'Enter a triathlon.',
    'Write down some 1-, 3-, and 5-year goals.',
    'Train for a 10km race.',
    'Work on your math skills.',
    'Go to the gym.',
    'Try to eat healthy all day—or all week!',
    'See what courses are available at your local higher education center.',
    'Make a small investment, e.g., shares, gold bullion bar.',
    'Give your brain a workout. Do a puzzle in the paper or take a grammar quiz online.',
    'Make a cake without following a recipe and see how it turns out.',
    'Rearrange your furniture.',
    'Buy your town local produce.',
    'Have a Nerf or BB gun battle. Make sure you wear suitable clothing!',
    'Rent a movie series and buy a big bag of snacks to eat as you binge.',
    'Plant vegetables. Look online to see what you can plant this month.',
    'Make homemade ice cream.',
    'Lie down and listen to music.',
    'Make a list of things you both want to achieve in the next ten years.',
]

var truth = [

  'Name ten body parts that your partner likes to kiss',
'Say a list of 10 items or things you bought and never used or regretted buying.',
'If you were the opposite sex for one hour, what would you do?',
'What was the most embarrassing moment of your life?',
'Have you ever been humiliated? Explain what happened and how you felt',
'Describe the strangest dream you’ve had in your life',
'Which player would you like to swap lives with for a week?',
'What physical feature do you get complimented on the most?',
'What is that one thing you would never do even if someone offered you all of the money in the world?',
'Among all the people in this room, which guy/girl would you like to date?',
'Who in the room do you think would be a bad date?',
'What is the quality or characteristic that would like to change about you?',
'Have you fallen in love with a friend of your partner? Has anyone noticed?',
'What do you think that your boyfriend/girlfriend thinks about marriage?',
'What was the craziest thing that has happened to you in a mall?',
'Mention the most annoying experience in some shopping.',
'What is the meanest thing you have done in your life?',
'Have you ever thought of cheat on your boyfriend/girlfriend?',
'Have you ever lied to your partner to avoid an intimate moment, for example, say that you feel sick?',
'What is the worst rumor or gossip you said or repeated and at the end was something wrong?',
'What was the most disgusting joke ever played with someone?',
'What’s your wildest fantasy?',
'Have you ever peed in a pool?',
'What is the most stupid thing you’ve done in front of a crowd?',
'What’s the first thing you would do if you were invisible?',
'Have you ever been hinted or has overstepped someone of the same sex? What happened, how did you react?',
'Which of the players in this group considered to have the most sensual and daring clothes?',
'Who do you think is the worst party dress? What would you recommend?',
'You might think that someone of your friends or family made a terrible decision for life says who and what s/he did.',
'Say who (here) has a wrong partner or does not suit him.',
'If you were marooned on an island with one person whom you know personally, who would like it to be that person?',
'He mentions something that ever done and that you did not want to be known',
'What is the dumbest thing you’ve said your partner while on intimacy?',
'Have you ever picked your nose and eaten it?',
'Which of the people who are in this game, considered to have the best body?',
'Which of the people who are in this game, believes it has lately deteriorated their physical appearance: his body, his dress?',
'If you could suddenly become invisible, what more naughty things you like to do?',
'If your crush told you he liked your best friend, what would you do?',
'What if your best friend told you that she liked your crush?',
'If you knew your friends boyfriend was cheating on her, what would you do?',
'Have you ever told a lie about your best friend to make yourself look better?',
'What was your first impression of [fill in the name of a person in the room]?',
'If you had to date someone elses boyfriend, who would it be?',
'Whos hotter? You or your friend?',
'Have you ever shared your friends secret with someone else?',
'Rate everyone in the room from 1 to 10, with 10 being the hottest.',
'Would you share a toothbrush with your best friend?',
'Rate everyone in the room from 1 to 10, with 10 being the best personality.',
'Have you ever ignored a friends text? Why did you do it?',
'Have you ever lied to your best friend?',
'Would you let a friend cheat on a test?',
'If your friend asked you to lie for her and you knew you would get in trouble, would you do it?',
'If one of your friends were cheating with your other friends boyfriend, what would you do?',
'Would you ditch your friends if you could become the most popular girl in school?',
'If you had to choose, who would you stop being friends with?',
'Name one thing you would change about each person in this room.',
'If you had to trade your friend in for the celebrity crush of your dreams, which friend would you choose?',
'What was your first impression of your best friends boyfriend?',
'What do you think about him now?',
'Have you ever thought about ditching your friend for a boy?',
'If someone asked you what your best friend is like, how would you describe her?',
'You win a trip and are allowed to bring two people. Who do you pick?',
'On an overnight trip, would you rather share a bed with your best friend or her boyfriend?',
'If you could swap one physical feature with your best friend, what would that be?',
'Have you ever told a secret you were told to keep?',
'If your best friend had B.O., would you tell her?',
'What is the most annoying thing about your best friend?',
'Who do you think your friend should date instead of her current boyfriend?',
'If she doesnt have a boyfriend, who do you think she should date?',
'Do you think your friends boyfriend is hot?',
'Would you hook up with him if you knew she would never find out?',
'Have you ever ditched your friend for a boy?',
'If your friend and your boyfriend were both dying in front of you, who would try to save first?',
]
  

var dare = [
  'Go up to someone and scare them.',
'Very affectionately kiss another participant (the rest can choose whom).',
'Give a massage to a companion for 5 minutes.',
'Eat a tablespoon of butter.',
'Asks for money on the street telling a funny story and nothing credible and board 50$.',
'Sing and dance in the street like crazy.',
'Become the slave of another player of your choosing for 5 mins.',
'Embrace the first passing through the street.',
'Dance with a broom or mop.',
'For guys: Briefly walk like a lady in high heels.',
'Climb to sing in the bar of a bar.',
'Declare who is your true love.',
'Tell something very intimate.',
'Sing the alphabet without moving your mouth',
'Do your best president impression.',
'Yell out the first word that comes to your mind right now.',
'Call the pizza place and order 300 sardine pizzas.',
'Once you have your eyes closed, feel someone’s face and guess who they are.',
'Make up a story about the item to your right.',
'Sing everything you say for the next 10 minutes.',
'Give a foot massage to someone present.',
'Give the person to your left a hickey.',
'Say the alphabet backward in 15 seconds.',
'Ask a random stranger to make out with you.',
'Act like you do not understand your language until your next turn (come up with your language).',
'Do pushups until it’s your turn again.',
'Wear a finger mustache for the next 5 minutes.',
'Eat a raw egg.',
'Bark like a dog.',
'Sing a song all the way through to the end.',
'Dance wildly to your favorite song.',
'Act like a dog and get petted by everyone.',
'Get a shower with all your clothes on.',
'Draw a face around your belly button.',
'Let someone write a word on your forehead in permanent marker.',
'Post an embarrassing picture of yourself online.',
'Put ice cube down bra or underwear and wait till melts.',
'Act like an old lady or an old man.',
'Spin around ten times, when you get done, try to walk in a straight line.',
'Go a whole minute without blinking.',
'Say “banana” after everything you say until it is your turn again.',
'Act like a monkey until it is your turn again.',
'Do a headstand for one minute.',
'Let someone put lipstick on your lips.',
'Eat something and then talk with your mouth full.',
 'Drink a glass of wine in less than 15 seconds',
 'Brush the teeth of the person sitting next to you.',
'Stuff ice inside your bra and leave it there for 60 seconds.',
'Sit on the lap of a guy for 10 minutes.',
 'Shave the legs of a man.',
 'Apply peanut butter to your face.',
 'Fill your mouth with water and try singing a song',
 'Call up your crush and declare your love for him.',
 'Striptease for thirty whole seconds.',
 'Make an obscene phone call to a random number.',
 'Remove the socks of a person sitting next to you with your teeth.',
 'Eat a raw egg with chocolate.',
'Bark like a dog and post it to your Instagram story.',
'Remove your panties and give it to a guy.',
'Yell at the top of your voice.',
 'Stuff ice cubes in the mouth for a minute.',
'Lick a bar of soap.',
'Take off one item of clothing.',
'Wet your hair and apply shampoo, but don’t rinse it off.',
'Blow in someone’s ear',
 'Show everything that’s in your purse',
 'Talk continuously for ten whole minutes',
 'Let someone else do you a makeup',
 'Have someone wrap tape around your neck',
 'Jump rope 150 times',
'Post a 1000 word Facebook status for no reason',
'Lick the floor.',
 'Cling to someone’s leg.',
'Talk with your tongue sticking out.',
'Hop around the room.',
'Go out on the road and say ‘I LOVE YOU’ to the first person you see.',
 'Call your crush and tell her mom that you like her daughter.',
 'Eat a piece of dog or cat food',
 'Kiss a stuffed animal like it is your crush.',
 'Carry the person to your left around the room',
'Draw a bunny on your face with only lipstick. Don’t look in the mirror.',
 'Do 40 pushups in less than a minute.',
'Speak with a fake accent for the rest of the game',
'Have someone to call a random person in the phone book and pretend to be her BF.',
'Write about a dirty fantasy you would never actually do in real life.',
'Pretend like you’re in a Toyota commercial. Sing, “I love what you do for me, TOYOTA!” and jump into the air.',
'Get someone to tie you down so you can’t move. Have them melt ice cubes all over your body.',
'Go out and drive your car in reverse gear for at least 25 yards, without stopping.',
'Go outside and dance like a cowboy.',
'Smell the feet of everyone in the room',
'Show everything that is in your wallet',
'Drink a glass of wine in 10 seconds',
'Peel a potato with your teeth',
 'Most the most embarrassing photo of yours, as FB profile picture.',
'Apply petroleum jelly on your face and sit for 30 mins',


]
function newList() {
    var randomNumber = Math.floor(Math.random() * (list.length));
    document.getElementById('listDisplay').innerHTML = list[randomNumber];
    }
function truthList() {
    var randomNumber = Math.floor(Math.random() * (truth.length));
    document.getElementById('listDisplay2').innerHTML = truth[randomNumber];
    }

function dareList() {
    var randomNumber = Math.floor(Math.random() * (dare.length));
    document.getElementById('listDisplay2').innerHTML = dare[randomNumber];
    }



